# Generated by Django 5.1.4 on 2024-12-27 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='last_name',
            new_name='last_name_employee',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='name',
            new_name='name_employee',
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_spent', models.DateField()),
                ('description_spent', models.CharField(max_length=250)),
                ('amount_spent', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.departments')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employees')),
            ],
        ),
    ]
